find_program(CLANG_TIDY_EXECUTABLE clang-tidy REQUIRED)

if(CLANG_TIDY_EXECUTABLE)
    message(STATUS "Found clang-tidy = ${CLANG_TIDY_EXECUTABLE}")
    file(GLOB_RECURSE SOURCE ${CMAKE_SOURCE_DIR}/lib/*.cpp ${CMAKE_SOURCE_DIR}/lib/*.h*)
    file(GLOB_RECURSE HEADER ${CMAKE_SOURCE_DIR}/include/*.h*)
    add_custom_target(tidy
    COMMAND ${CLANG_TIDY_EXECUTABLE} -p=${CMAKE_BINARY_DIR} --export-fixes=${CMAKE_BINARY_DIR}/tidy.fix ${SOURCE} ${HEADER} ${TEST_SOURCE}
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
    )
endif(CLANG_TIDY_EXECUTABLE)
