
find_program(CLANG_FORMAT_EXECUTABLE clang-format REQUIRED)

if(CLANG_FORMAT_EXECUTABLE)
    message(STATUS "Found clang-format = ${CLANG_FORMAT_EXECUTABLE}")
    file(GLOB_RECURSE TEST_SOURCE ${CMAKE_SOURCE_DIR}/tests/*.cpp ${CMAKE_SOURCE_DIR}/tests/*.h*)
    file(GLOB_RECURSE SOURCE ${CMAKE_SOURCE_DIR}/lib/*.cpp ${CMAKE_SOURCE_DIR}/lib/*.h*)
    file(GLOB_RECURSE HEADER ${CMAKE_SOURCE_DIR}/include/*.h*)
    add_custom_target(format
    COMMAND ${CLANG_FORMAT_EXECUTABLE} -i ${SOURCE} ${HEADER} ${TEST_SOURCE}
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
    )
endif(CLANG_FORMAT_EXECUTABLE)
